### PR TITLE
Add aria2

### PR DESCRIPTION
**Pull request by bbhtt**
Let's see if this works. I've never used this feature of Liferea.

### CODE REVIEW

**Comment by bbhtt** [comment]
By default downloads go into `$HOME`, but that involves giving too much permission. I think we need to patch the default aria2c command liferea uses to make it use `$HOME/Downloads` or add something in the readme here.

**Comment by mikelolasagasti** [comment]
Patching would be easier for everyone.

**Comment by bbhtt** [comment]
Seems to work.

I can't specify two variables like `${XDG_DOWNLOAD_DIR:-$HOME/Downloads}`, it says download completed, but the file goes nowhere. My guess is the shell's variable expansion doesn't work here. Specifying only `$XDG_DOWNLOAD_DIR` (although more correct) isn't an option because it's not always set in the environment.

Anyways, if people have a different download directory set, they can always use the custom command I guess.

**Comment by bbhtt** [comment]
Ok it works with `/bin/sh -c 'aria2c -d ${XDG_DOWNLOAD_DIR:-$HOME/Downloads} %s'`

**Comment by bbhtt** [comment]
I think I can't push directly to the `beta` branch as it is protected. I'll open a separate PR to sync master and beta

**Comment by bbhtt** [comment]
Hey @lwindolf I wanted to ask if you want this patch upstream ie. switch the default or the first one in the list to aria2c?

Steadyflow is not really developed anymore https://launchpad.net/steadyflow last release in 2012, last activity in 2018 and is not packaged by many distributions eg. https://pkgs.org/search/?q=steadyflow shows only a third pary Arch repo packaging it.

While aria2 is actively developed https://github.com/aria2/aria2 last commit 2 weeks ago, last release from 2021 and is packaged by almost all distributions https://pkgs.org/search/?q=aria2

aria2 is also kind of ubiquitous like curl/wget (maybe not that much).

A cli program is also much easier to package along with snap/flatpaks than a GUI one and I imagine it'd be easier to put it in "recommends" for distro maintainers as well. aria2c depends on very low level libraries like gnutls, libssh2 etc. ie. not very heavy compared to some of the other ones in the list.

It's not a big deal to maintain this, but I think it'd improve the experience a tiny bit.

**Pull request merged**
