### PR TITLE
Update Liferea to 1.14.0

### PR DESCRIPTION
**Pull request by bbhtt**
Updated appdata is now included in the release https://github.com/lwindolf/liferea/blob/3cdf6f7a85300c9a60c73f6654845c590eadf86c/net.sourceforge.liferea.appdata.xml.in#L108

### CODE REVIEW

**Comment by mikelolasagasti** [comment]
@bbhtt thanks, one more time, to taking care of this!

The PR is correct, but I'm not sure if flathub build is correct, as it didn't report the successful build. Do you know how to re-trigger the build? worst case force-pushing again should do the trick I guess.

**Comment by bbhtt** [comment]
@mikelolasagasti Hi, can you please trigger a rebuild by signing in with Github on https://buildbot.flathub.org/#/apps/net.sourceforge.liferea and hitting the "start build"? Thanks.

The publish job failed for some reason

https://buildbot.flathub.org/#/builders/6/builds/16641

`| Job failed: InternalError: Command "flatpak" "build-commit-from" "--force" "--no-update-summary" "--gpg-homedir=/var/lib/flat-manager/.gnupg" "--gpg-sign=4184DD4D907A7CAE" "--src-repo=/tank/repo/builds/129072" "/tank/repo/stable" exited unsuccesfully: error: Failure signing commit file: Pinentry: Inappropriate ioctl for device`

so Flathub still is stuck to the old build:

```
flatpak remote-info flathub net.sourceforge.liferea
        ID: net.sourceforge.liferea
       Ref: app/net.sourceforge.liferea/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 11.8 MB
 Installed: 25.1 MB
   Runtime: org.gnome.Platform/x86_64/42
       Sdk: org.gnome.Sdk/x86_64/42

    Commit: 44093433d260410d45987f72320458b71351bb8db824e23e8abb57bfc14e82ab
    Parent: cfb171c039829e4b052c602e9753ac1bf5e3e2869d8691ba579ec6a68ae6feba
   Subject: Update Liferea to 1.13.9 (dfc16240)
      Date: 2022-07-26 19:35:46 +0000
```

**Comment by mikelolasagasti** [comment]
Done: https://buildbot.flathub.org/#/buildrequests/63865

**Comment by bbhtt** [comment]
> Done:
https://buildbot.flathub.org/#/buildrequests/63865


Unfortunately it failed again with a 502 server error. You'll need to trigger another build. https://buildbot.flathub.org/#/builders/6/builds/16817

**Comment by mikelolasagasti** [comment]
Seems it worked work this time https://buildbot.flathub.org/#/builders/2/builds/5889

**Comment by bbhtt** [comment]
Yep, thanks!

**Pull request merged**
