### PR TITLE
Update Liferea to 1.13.5; runtime to 40

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by mikelolasagasti** [comment]
thanks @bbhtt !

You'll need to update the `0001-Update-AppData-with-release-dates.patch` patch file to include info about the 1.13.5 release.

**Comment by bbhtt** [comment]
> You'll need to update the `0001-Update-AppData-with-release-dates.patch` patch file to include info about the 1.13.5 release.

Looks like it wasn't updated in upstream; I'm submitting a PR there first.

**Comment by bbhtt** [comment]
Seems to be working fine on my end.

**Comment by mikelolasagasti** [comment]
Works for me also, thanks @bbhtt

**Comment by bbhtt** [comment]
Looks like the version string on Flathub didn't get updated somehow https://flathub.org/apps/details/net.sourceforge.liferea .. while on my system `flatpak` reports the correct version:

```
$ flatpak list|grep liferea
Liferea	net.sourceforge.liferea	1.13.5	stable	flathub	user
```

**Comment by mikelolasagasti** [comment]
It shows 1.13.5 on the webpage for me, updated on April 9, 2021

**Pull request merged**
